"""Add score porperty in ReplyItem model

Revision ID: 4cfd1638cf44
Revises: 2e51bb4612b8
Create Date: 2024-12-28 13:52:05.845251

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4cfd1638cf44'
down_revision = '2e51bb4612b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replyitem', sa.Column('score', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replyitem', 'score')
    # ### end Alembic commands ###
