"""Description in ItemBase now no limits length

Revision ID: a80e959642c0
Revises: 1525a8728c34
Create Date: 2024-12-28 13:52:05.845251

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a80e959642c0'
down_revision = '1525a8728c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
