"""Add cascade delete to Item-ReplyItem relationship

Revision ID: ce6dee4c048e
Revises: 39880b21d311
Create Date: 2024-12-28 13:52:05.845251

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ce6dee4c048e'
down_revision = '39880b21d311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('replyitem_item_id_fkey', 'replyitem', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('replyitem_item_id_fkey', 'replyitem', 'item', ['item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
